services:
  # Backend API
  - type: web
    name: lacanasta-api
    env: node
    plan: free # Plan gratuito de Web Service
    rootDir: api
    # Eliminamos TypeScript del servidor para ahorrar memoria. Solo generamos cliente Prisma.
    buildCommand: npm install && cp prisma/schema.prod.prisma prisma/schema.prisma && npx prisma generate
    # Ejecutamos código PRE-COMPILADO (dist) que subimos desde local. Mucho más ligero y estable.
    startCommand: node dist/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lacanasta-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  # Base de Datos (PostgreSQL) - Plan Gratuito
  - name: lacanasta-db
    databaseName: lacanasta
    user: lacanasta
    plan: free
