name = "la-canasta-api"
main = "src/server.ts"
compatibility_date = "2024-04-03"

[[d1_databases]]
binding = "DB"
database_name = "lacanasta_api_db"
database_id = "38ef1fc3-4af6-40d4-bf06-72252bcf685d"

[vars]
JWT_SECRET = "supersecretkey"

[observability]
enabled = true
